### PR TITLE
add option to display loco name instead of dcc address

### PR DESCRIPTION
**Pull request by FancyRedCat**
Add a option to display loco name instead of the DCC address.
Maybe there is an more efficent way to get the loco name.

### CODE REVIEW

**Comment by flash62au** [comment]
hi,
a) once you find it in the while loop, you should have a 'break' so that it doesn't keep going through the rest of the loop.
b) is there a reason why you used 'while' rather than a simple 'for'?
c) the example should be commented out by default.

The side effect of this is that it will show the matching name of a roster entry name, even if you entered it as an address, not selected from the roster. So the functions will not have loaded.  - Not a big issue.  Just saying.

**Comment by flash62au** [comment]
e.g. 
e.g.
for(int i=0; i<maxRoster; i++) {
   if (String(rosterAddress[i]) == locoNumber) {
        if (rosterName[i] != "") {
          locoNumber = rosterName[i] + "  ";
        }
       break;
}

**Comment by flash62au** [comment]
a) sorry I missed the =-1 which will act as a break.

**Comment by FancyRedCat** [comment]
hi,
a) the i=-1; was my break, but a real break; is easier to read
b) I don't prefere for the one or the other. So we can change that
c) that's my fault
d) if there are loco names that contain a space, it's hard to distinguish the space in the name and the space between the names. I created another config option. This resolves also an issue with the inverted consist direction marker '.
`#define CONSIST_SPACE_BETWEEN_LOCOS " | "` isn't working because "`|`" isn't in the font :/

Hm, my controller can display the function labels (if defined in JMRI). It doesn't matter if I select the loco from the roster list or type in the dcc address. (even in my nfc test the labels are displayed)

**Comment by flash62au** [comment]
a) yes, sorry I missed that.  Break is clearer though.
b) I have use for loops everywhere else, so I would prefer that for consistency
d) what about a comma?

e) humm.. oh well.  all good.

**Pull request merged**
